- name: Installing software-properties-common
  apt:
    name: software-properties-common
    state: latest
    update_cache: yes

- name: Add deadsnakes repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Installing Python3.8
  apt:
    name: python3.8
    state: latest
    update_cache: yes
