- name: Installing with apt
  apt:
    name: software-properties-common
    state: latest
    update_cache: yes

- name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Installing with apt
  apt:
    name: python3.8
    state: latest
    update_cache: yes
